# Generated by Django 5.1.5 on 2025-04-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
